export const defaultAreaId = "parramatta";

export const areaConfigs = {
  parramatta: {
    id: "parramatta",
    name: "Parramatta, NSW",
    region: "Greater Sydney",
    catchment: "Parramatta River",
    lat: -33.8,
    lon: 151.0,
    relevantStations: {
      weather: ["Parramatta"],
      rainfall: ["67111"],
      river: [
        "Parramatta River at Riverside Theatre",
        "Parramatta River at Marsden Weir",
        "Darling Mills Creek at North Parramatta",
      ],
    },
  },
  "north-parramatta": {
    id: "north-parramatta",
    name: "North Parramatta, NSW",
    region: "Greater Sydney",
    catchment: "Darling Mills Creek / Parramatta River",
    lat: -33.79,
    lon: 151.01,
    relevantStations: {
      weather: ["Parramatta"],
      rainfall: ["67111"],
      river: [
        "Darling Mills Creek at North Parramatta",
        "Parramatta River at Riverside Theatre",
      ],
    },
  },
  toongabbie: {
    id: "toongabbie",
    name: "Toongabbie, NSW",
    region: "Greater Sydney",
    catchment: "Toongabbie Creek",
    lat: -33.79,
    lon: 150.95,
    relevantStations: {
      weather: ["Parramatta"],
      rainfall: ["567065"],
      river: [
        "Toongabbie Creek at Johnstons Bridge",
        "Toongabbie Creek at Briens Rd",
        "Toongabbie Creek at Redbank Road",
      ],
    },
  },
};

export const stationCatalog = [
  {
    id: "weather-parramatta",
    type: "weather",
    sourceType: "official_backup",
    provider: "Bureau of Meteorology",
    stationId: "94764",
    name: "Parramatta",
    stationName: "Parramatta",
    areaIds: ["parramatta", "north-parramatta", "toongabbie"],
    lat: -33.8,
    lon: 151.0,
  },
  {
    id: "rainfall-67111",
    type: "rainfall",
    sourceType: "primary_live_gauge",
    provider: "City of Parramatta FloodSmart",
    stationId: "67111",
    name: "Burnside Homes",
    stationName: "Burnside Homes",
    stationNumber: "67111",
    areaIds: ["parramatta", "north-parramatta"],
    lat: -33.7916,
    lon: 151.0179,
  },
  {
    id: "rainfall-567065",
    type: "rainfall",
    sourceType: "primary_live_gauge",
    provider: "City of Parramatta FloodSmart",
    stationId: "567065",
    name: "Toongabbie Bowling Club",
    stationName: "Toongabbie Bowling Club",
    stationNumber: "567065",
    areaIds: ["toongabbie"],
    lat: -33.784,
    lon: 150.9525,
  },
  {
    id: "river-riverside-theatre",
    type: "river",
    sourceType: "primary_live_gauge",
    provider: "City of Parramatta FloodSmart",
    stationId: "567057",
    name: "Parramatta River at Riverside Theatre",
    stationName: "Parramatta River at Riverside Theatre",
    areaIds: ["parramatta", "north-parramatta"],
    lat: -33.814,
    lon: 151.004,
  },
  {
    id: "river-marsden-weir",
    type: "river",
    sourceType: "primary_live_gauge",
    provider: "City of Parramatta FloodSmart",
    stationId: "567107",
    name: "Parramatta River at Marsden Weir",
    stationName: "Parramatta River at Marsden Weir",
    areaIds: ["parramatta"],
    lat: -33.809,
    lon: 150.999,
  },
  {
    id: "river-darling-mills",
    type: "river",
    sourceType: "primary_live_gauge",
    provider: "City of Parramatta FloodSmart",
    stationId: "567112",
    name: "Darling Mills Creek at North Parramatta",
    stationName: "Darling Mills Creek at North Parramatta",
    areaIds: ["parramatta", "north-parramatta"],
    lat: -33.788,
    lon: 151.009,
  },
  {
    id: "river-toongabbie-johnstons",
    type: "river",
    sourceType: "primary_live_gauge",
    provider: "City of Parramatta FloodSmart",
    stationId: "567058",
    name: "Toongabbie Creek at Johnstons Bridge",
    stationName: "Toongabbie Creek at Johnstons Bridge",
    areaIds: ["toongabbie"],
    lat: -33.785,
    lon: 150.95,
  },
  {
    id: "river-toongabbie-briens",
    type: "river",
    sourceType: "primary_live_gauge",
    provider: "City of Parramatta FloodSmart",
    stationId: "567074",
    name: "Toongabbie Creek at Briens Rd",
    stationName: "Toongabbie Creek at Briens Rd",
    areaIds: ["toongabbie"],
    lat: -33.795,
    lon: 150.963,
  },
  {
    id: "river-toongabbie-redbank",
    type: "river",
    sourceType: "primary_live_gauge",
    provider: "City of Parramatta FloodSmart",
    stationId: "567056",
    name: "Toongabbie Creek at Redbank Road",
    stationName: "Toongabbie Creek at Redbank Road",
    areaIds: ["toongabbie"],
    lat: -33.804,
    lon: 150.943,
  },
];

export function listAreas() {
  return Object.values(areaConfigs).map((area) => ({
    id: area.id,
    name: area.name,
    region: area.region,
    catchment: area.catchment,
  }));
}

export function getAreaConfig(areaId = defaultAreaId) {
  return areaConfigs[areaId] ?? null;
}
